name: Run ESLint and automation tests

on:
  - push
  - pull_request
  
env:
  CI: true
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: npm install, build
      run: make install

    - name: ESLint check
      run: make lint
      
    - name: Automation test
      run: make tests
    
